# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.letsmeet.click
title: Let's Meet!
email: no-mail@example.com
author: (secret)
description: > # "Write an awesome description for your new site here.
    makes meeting humans easy.
copyright: 'Copyright &copy; 2015. All Rights Reserved.'
credits: ''

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/letsmeet_click
  - title: github
    url: https://github.com/letsmeet-click
